project:
  type: website
  output-dir: docs

website:
  title: "Projet de recherche, Université de Montréal"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Revue littérature.qmd
      - Données et méthodologie.qmd
      - Analyse descriptive.qmd
      - Analyses économétriques.qmd
      - Conclusion et discussion.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

