---
title: "Conclusion et discussion"
title-block-banner: false
author:
  - name: "Juliana Hubacova"
    url: https://github.com/julianahubacova
    affiliation: ECN3950_H23_UdeM
    orcid: 0000-0001-8128-783X
date: "2023-09-21"
citation: true
bibliography: references.bib
format :
    html : 
        df-print: kable
---
**Conclusion**
L’analyse économétrique conduite dans ce projet de recherche réalisé dans le but de constater un potentiel effet causal entre la légalisation de l’avortement et le taux d’emploi des femmes ne nous permet pas de conclure à une relation entre ces deux variables. Les résultats obtenus démontrent une baisse du taux d’emploi des femmes à la suite de la nouvelle loi instaurée mais ceci entre en contradiction avec notre hypothèse initiale selon laquelle les taux d’emploi des femmes augmente avec l’accès à l’avortement. Nos régressions n’ont pas retourné des coefficients statistiquement significatifs et donc cette baisse des taux d’emploi n’est pas attribuable à la légalisation de l’avortement mais pourrait être dû à d’autres facteurs externes et aux phénomènes économiques.


**Discussion**
Des améliorations à notre modèle de base pourraient être apportées notamment par l’ajout de variable de contrôle pour réduire le biais de variable omise (éducation des femmes, utilisation de la pilule contraceptive, …) Nous avons entrepris des recherches pour ajouter les taux d’éducation comme variable de contrôle dans notre modèle mais ces recherches ont été sans succès. Les taux d’éducation pour les femmes au Canada que nous avons trouvé commencent à partir des années 1990 seulement. Le manque de données et l’imprécision de celles-ci – notamment par la non prise en compte des avortement illégaux dans nos bases de données principales – ont potentiellement contribué à ce que nous ne trouvions pas d’effet significatif dans nos analyses économétriques. En ce qui concerne nos choix de groupe de traitement et de contrôle, une alternative au groupe de contrôle ‘les femmes de 45 ans et plus’ aurait pu être les hommes. Nous avons préféré utiliser les femmes de 45 ans et plus dont les taux d’avortement sont quasi nuls parce que nous estimions que la différence entre les taux d’emplois des hommes et des femmes cachait de nombreux autres facteurs telles que des opportunités d’emplois différentes, des inégalités salariales et de la discrimination de genre qui seraient difficile à prendre en compte. Toutefois, il serait intéressant de réaliser une analyse similaire utilisant les hommes comme groupe de contrôle pour comparer les différences dans les résultats. Bien que des améliorations puissent être effectuée sur notre modèle, nous pouvons tout de même conclure qu’aucun effet n’a été trouvé entre la légalisation de l’avortement et le taux d’emplois des femmes. 
